{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spring-petclinic-microservices-swagger.serviceAccountName" . }}
  labels:
{{ include "spring-petclinic-microservices-swagger.labels" . | nindent 4 }}
{{- end -}}
