{{- $_ := set . "appName" "admin-server" }}
        {{- $__ := set . "appPort" 9090 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-microservices-swagger.{{ .appName }}
  labels:
    app: {{ .appName }}
        {{- include "spring-petclinic-microservices-swagger.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .appName }}
        {{- include "spring-petclinic-microservices-swagger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
          {{- include "spring-petclinic-microservices-swagger.selectorLabels" . | nindent 8 }}
    spec:
            {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
            {{- toYaml . | nindent 6 }}
            {{- end }}
      securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .appName }}
          image: springcommunity/spring-petclinic-{{ .appName }}
          imagePullPolicy: IfNotPresent
          command: ["./dockerize"]
          args: ["-wait=tcp://discovery-server.svc.{{ .Values.clusterDNSsuffix }}:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
          ports:
            - containerPort: {{ .appPort}}
          resources:
            limits:
              memory: 512Mi
