{{- $_ := set . "appName" "discovery-server" }}
        {{- $__ := set . "appPort" 8761 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "spring-petclinic-microservices-swagger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .appPort }}
      targetPort: {{ .appPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .appName }}
